#!/usr/bin/env python3
"""
generate_full_sitemap.py (v2 — URL bug fixed)
JERRY 🤖 — 2026-08-12 10:55
Fixed: URL prefix duplication bug

Output: 
  /home/donald/.openclaw/workspace/stratronix-website-new/sitemap.xml (覆盖)
  /home/donald/.openclaw/workspace/exhibition-drop-flag-2026-08-12/sitemap-NEW-2026-08-12-v2.xml
"""
import os
import re
from datetime import datetime

ROOT = "/home/donald/.openclaw/workspace/stratronix-website-new"
SITEMAP_OUT = os.path.join(ROOT, "sitemap.xml")
SITEMAP_BACKUP = "/home/donald/.openclaw/workspace/exhibition-drop-flag-2026-08-12/sitemap-NEW-2026-08-12-v2.xml"

EXCLUDE_NAMES = {
    "404.html",
    "360_verify.html",
    "baidu_verify_codeva-f9joA45YuV.html",
    "google1234567890abcdef.html",
    "naver_verify.html",
    "shenma_verify.html",
    "toutiao_verify.html",
    "yandex_e5f7d6b34a469017.html",
    "yandex_verification.html",
}
EXCLUDE_DIRS = {"admin", "private", "tmp", "api", "node_modules", ".git", "archive", "source", "verification", "seo/verification"}

TODAY = datetime.now().strftime("%Y-%m-%d")


def file_to_url_path(rel_path):
    """Convert local file path to URL PATH (no scheme/host)."""
    rel_path = rel_path.lstrip("./")
    if rel_path.endswith(".html"):
        url_path = rel_path[:-5]
    else:
        url_path = rel_path
    if url_path == "index":
        url_path = ""
    elif url_path.endswith("/index"):
        url_path = url_path[:-6]
    # Ensure leading /
    if url_path and not url_path.startswith("/"):
        url_path = "/" + url_path
    return url_path


def priority_for(url_path):
    if url_path in ("/", "/zh"):
        return "1.0"
    if url_path in ("/products", "/zh/products", "/ai-agent", "/ai", "/ai-box", "/ai-china", "/ai-company", "/openclaw"):
        return "0.9"
    if url_path in ("/about", "/zh/about", "/contact", "/zh/contact"):
        return "0.8"
    if url_path.startswith("/zh/"):
        return "0.7"
    if url_path.startswith("/sales-support") and not re.search(r"/\d{4}-\d{2}-\d{2}/", url_path):
        return "0.7"
    if url_path.startswith("/cases") and url_path.count("/") == 2:
        return "0.7"
    return "0.6"


def changefreq_for(priority):
    if float(priority) >= 0.9:
        return "weekly"
    if float(priority) >= 0.7:
        return "monthly"
    return "monthly"


def main():
    print(f"Scanning {ROOT} ...")
    urls = []
    excluded_count = 0

    for root, dirs, files in os.walk(ROOT):
        dirs[:] = [d for d in dirs if d not in EXCLUDE_DIRS and not d.startswith(".")]

        for fname in files:
            if not fname.endswith(".html"):
                continue
            if fname in EXCLUDE_NAMES:
                excluded_count += 1
                continue

            abs_path = os.path.join(root, fname)
            rel_path = os.path.relpath(abs_path, ROOT)
            url_path = file_to_url_path(rel_path)
            priority = priority_for(url_path)
            changefreq = changefreq_for(priority)
            lastmod = datetime.fromtimestamp(os.path.getmtime(abs_path)).strftime("%Y-%m-%d")

            urls.append((url_path, lastmod, priority, changefreq, rel_path))

    urls.sort(key=lambda x: (-float(x[2]), x[0]))

    lines = ['<?xml version="1.0" encoding="UTF-8"?>']
    lines.append('<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"')
    lines.append('        xmlns:xhtml="http://www.w3.org/1999/xhtml">')
    lines.append("")
    lines.append(f"<!-- Generated by JERRY 🤖 — {TODAY} (汪总 10:40 '解决' 显式授权 LOCKED) -->")
    lines.append(f"<!-- {len(urls)} URLs (excluded: {excluded_count}) -->")
    lines.append("")

    for url_path, lastmod, priority, changefreq, src in urls:
        lines.append("<url>")
        lines.append(f"  <loc>https://www.stratronix.ai{url_path}</loc>")
        lines.append(f"  <lastmod>{lastmod}</lastmod>")
        lines.append(f"  <changefreq>{changefreq}</changefreq>")
        lines.append(f"  <priority>{priority}</priority>")
        lines.append("</url>")

    lines.append("")
    lines.append("</urlset>")

    xml_content = "\n".join(lines)

    with open(SITEMAP_BACKUP, "w", encoding="utf-8") as f:
        f.write(xml_content)

    with open(SITEMAP_OUT, "w", encoding="utf-8") as f:
        f.write(xml_content)

    print(f"\n✓ Deployed: {SITEMAP_OUT}")
    print(f"  Backup: {SITEMAP_BACKUP}")
    print(f"  URLs: {len(urls)}")
    print(f"  Size: {os.path.getsize(SITEMAP_OUT)} bytes")

if __name__ == "__main__":
    main()